export const contactInfo = {
  phone: "963968467163",
  lan: "042521251",
  email: "info@nawar.site",
  location: "Saudi Arabia - Riyadh",
  facebook: "https://www.facebook.com/share/168Lb9QHb5/",
  instagram:
    "https://www.instagram.com/phoenician2025?igsh=MW00cHNuazl2NG9pOA==",
  googleMap:
    "https://www.google.com/maps/place/%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6+%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9%E2%80%AD/@24.7248315,47.1521875,10z/data=!3m1!4b1!4m12!1m5!3m4!2zMjXCsDE1JzM4LjUiTiA1NcKwMjAnMDYuMiJF!8m2!3d25.2606944!4d55.3350556!3m5!1s0x3e2f03890d489399:0xba974d1c98e79fd5!8m2!3d24.7135517!4d46.6752957!16zL20vMGRsbV8?authuser=0&entry=ttu&g_ep=EgoyMDI1MDgwNi4wIKXMDSoASAFQAw%3D%3D",
  embeddedMap:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d231949.1192260541!2d46.91254826027999!3d24.719841855602613!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e2f03890d489399%3A0xba974d1c98e79fd5!2z2KfZhNix2YrYp9i2INin2YTYs9i52YjYr9mK2Kk!5e0!3m2!1sar!2snl!4v1754987710207!5m2!1sar!2snl",
  host:
    process.env.NODE_ENV === "production"
      ? process.env.NEXT_PUBLIC_APP_BASE_URL
      : "http://localhost:3000",
} as const;
export const seo = {
  siteName: "Naya",
  logoUrl: `${contactInfo.host}/logo.png`, // Adjust path to your actual logo file
  home: {
    description:
      "Naya Marketing Management offers innovative solutions to transform your ideas into exceptional digital experiences.",
    keywords: [
      "Naya",
      "Digital Agency",
      "Digital Marketing",
      "Creative Solutions",
      "Innovative Technology",
      "Digital Experiences",
      "Web Development",
      "User Engagement",
      "Digital Transformation",
      "Creative Digital Agency",
      "وكالة رقمية",
      "تسويق رقمي",
      "حلول إبداعية",
      "تقنية مبتكرة",
      "تجارب رقمية",
      "تطوير الويب",
      "تفاعل المستخدم",
      "تحول رقمي",
      "وكالة رقمية إبداعية",
    ],
  },
  about: {
    title: "About Us",
    description:
      "Learn more about Naya Marketing Management, our mission, vision, and the dedicated team driving exceptional digital experiences.",
    keywords: [
      "About Naya",
      "Digital Agency Story",
      "Company Mission",
      "Creative Team",
      "Digital Experts",
      "Industry Experience",
      "Innovative Solutions",
      "Brand History",
      "Digital Innovation",
      "Team Expertise",
      "حول Naya",
      "قصة الوكالة الرقمية",
      "مهمة الشركة",
      "فريق إبداعي",
      "خبراء رقميون",
      "خبرة صناعية",
      "حلول مبتكرة",
      "تاريخ العلامة التجارية",
      "ابتكار رقمي",
      "خبرة الفريق",
    ],
  },
  services: {
    title: "Our Services",
    description:
      "Explore the range of digital solutions and creative services offered by Naya. Discover how our innovative marketing, branding, and digital experiences can elevate your business.",
    keywords: [
      "Digital Marketing",
      "Branding",
      "Web Development",
      "Creative Solutions",
      "Marketing Strategies",
      "Social Media Management",
      "SEO",
      "Content Marketing",
      "Graphic Design",
      "User Experience Design",
      "التسويق الرقمي",
      "العلامة التجارية",
      "تطوير المواقع",
      "الحلول الإبداعية",
      "استراتيجيات التسويق",
      "إدارة وسائل التواصل الاجتماعي",
      "تحسين محركات البحث",
      "تسويق المحتوى",
      "التصميم الجرافيكي",
      "تصميم تجربة المستخدم",
    ],
  },
  contact: {
    title: "Contact Us",
    description:
      "Get in touch with Naya Marketing Management for exceptional digital solutions. Find our contact details and reach out today.",
    keywords: [
      "Contact Naya",
      "Digital Agency Contact",
      "Get in Touch",
      "Client Support",
      "Digital Consultation",
      "Request a Quote",
      "Business Inquiries",
      "Customer Service",
      "Agency Contact",
      "Connect with Us",
      "اتصل بـ Naya",
      "اتصال الوكالة الرقمية",
      "تواصل معنا",
      "دعم العملاء",
      "استشارة رقمية",
      "طلب عرض سعر",
      "استفسارات الأعمال",
      "خدمة العملاء",
      "جهة اتصال الوكالة",
      "تواصل معنا",
    ],
  },
  startProject: {
    title: "Start a Project",
    description:
      "Ready to bring your vision to life? Get started with Naya Marketing Management and let’s create something extraordinary together.",
    keywords: [
      "Start Project",
      "Project Inquiry",
      "Digital Project",
      "Consultation",
      "Project Initiation",
      "Creative Collaboration",
      "Marketing Project",
      "Digital Transformation",
      "Innovation",
      "Partnership",
      "بدء المشروع",
      "استفسار المشروع",
      "مشروع رقمي",
      "استشارة",
      "بدء التعاون",
      "تواصل إبداعي",
      "مشروع تسويقي",
      "التحول الرقمي",
      "الابتكار",
      "الشراكة",
    ],
  },
  privacy: {
    title: "Privacy Policy",
    description:
      "Read the privacy policy for Naya to learn how we collect, use, and protect your personal information.",
    keywords: [
      "Privacy Policy",
      "Data Protection",
      "User Privacy",
      "Digital Security",
      "Naya Privacy",
      "Legal Information",
      "Data Security Policy",
      "سياسة الخصوصية",
      "حماية البيانات",
      "خصوصية المستخدم",
      "أمان رقمي",
      "خصوصية Naya",
      "معلومات قانونية",
      "سياسة أمان البيانات",
    ],
  },
  terms: {
    title: "Terms & Conditions",
    description:
      "Review the terms and conditions governing the use of Naya website and services.",
    keywords: [
      "Terms of Service",
      "User Agreement",
      "Service Terms",
      "Digital Agency Terms",
      "Legal Conditions",
      "Naya Terms",
      "Service Agreement",
      "شروط الخدمة",
      "اتفاقية المستخدم",
      "شروط الخدمة",
      "شروط الوكالة الرقمية",
      "شروط قانونية",
      "شروط Naya",
      "اتفاقية الخدمة",
    ],
  },
};
export const navItems = [
  { href: "/portfolio/All", label: "Portfolio" },
  { href: "/about", label: "About Us" },
  { href: "/contact", label: "Contact" },
] as const;
